/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Master Galanodel (https://sketchfab.com/Master_Galanodel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/allay-redesigned-65a09bda6056476fa333d9cd4bed5920
Title: Allay (redesigned)
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import AllayScene from "../assets/3d/allay_redesigned.glb";
import { useFrame } from "@react-three/fiber";
const Allay = ({ worldPosRot, BeePosition, ...props }) => {
  const AllayRef = useRef();
  const { nodes, materials, animations } = useGLTF(AllayScene);
  const { actions } = useAnimations(animations, AllayRef);

  useFrame(() => {
    actions["animation.master_galanodels_allay.fly"].play();
    if (worldPosRot) {
      // Adjusting the x and z positions
      AllayRef.current.position.x =
        worldPosRot.worldPosition[0] + BeePosition.position[0];
      AllayRef.current.position.z =
        worldPosRot.worldPosition[2] + BeePosition.position[2];

      // Oscillating the y position using a sine wave
      const yOffset = Math.sin(Date.now() * 0.001) * 0.2;
      AllayRef.current.position.y =
        worldPosRot.worldPosition[1] + BeePosition.position[1] + yOffset;

      // Setting the rotation
      AllayRef.current.rotation.x = BeePosition.rotation[0];
      AllayRef.current.rotation.y = BeePosition.rotation[1];
      AllayRef.current.rotation.z = BeePosition.rotation[2];
    }
  });
  return (
    <group ref={AllayRef} {...props}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, Math.PI]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="_42">
                <group name="body_41" position={[0, 0.375, 0]}>
                  <group name="body_0" position={[0, -0.375, 0]}>
                    <mesh
                      name="Object_6"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_6.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name="head_17" position={[0, 0.094, 0]}>
                    <group name="head_1" position={[0, -0.469, 0]}>
                      <mesh
                        name="Object_9"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_9.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="head_2" rotation={[0.087, 0, 0]}>
                      <mesh
                        name="Object_11"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_11.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="hairtip_6" position={[0, 0.219, 0.063]}>
                      <group name="hairtip_5" position={[0, -0.688, -0.063]}>
                        <mesh
                          name="Object_14"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_14.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="eye_0_8" position={[0.047, 0.109, -0.125]}>
                      <group name="eye_0_7" position={[-0.047, -0.578, 0.125]}>
                        <mesh
                          name="Object_17"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_17.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group
                      name="eyebrow_0_10"
                      position={[0.047, 0.172, -0.125]}
                    >
                      <group
                        name="eyebrow_0_9"
                        position={[-0.047, -0.641, 0.125]}
                      >
                        <mesh
                          name="Object_20"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_20.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group
                      name="eyebrow_1_12"
                      position={[-0.047, 0.172, -0.125]}
                    >
                      <group
                        name="eyebrow_1_11"
                        position={[0.047, -0.641, 0.125]}
                      >
                        <mesh
                          name="Object_23"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_23.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="eye_1_14" position={[-0.047, 0.109, -0.125]}>
                      <group name="eye_1_13" position={[0.047, -0.578, 0.125]}>
                        <mesh
                          name="Object_26"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_26.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="mouth_16" position={[0, 0.016, -0.125]}>
                      <group name="mouth_15" position={[0, -0.485, 0.125]}>
                        <mesh
                          name="Object_29"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_29.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="arm_left_21" position={[-0.063, 0.078, 0]}>
                    <group name="arm_left_18" position={[0.063, -0.453, 0]}>
                      <mesh
                        name="Object_32"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_32.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="hand_left_20" position={[-0.125, 0, 0]}>
                      <group name="hand_left_19" position={[0.188, -0.453, 0]}>
                        <mesh
                          name="Object_35"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_35.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="arm_right_25" position={[0.063, 0.078, 0]}>
                    <group name="arm_right_22" position={[-0.063, -0.453, 0]}>
                      <mesh
                        name="Object_38"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_38.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="hand_right_24" position={[0.125, 0, 0]}>
                      <group
                        name="hand_right_23"
                        position={[-0.188, -0.453, 0]}
                      >
                        <mesh
                          name="Object_41"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_41.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="tail_0_31" position={[0, -0.094, 0]}>
                    <group name="tail_0_26" position={[0, -0.281, 0]}>
                      <mesh
                        name="Object_44"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_44.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="tail_1_30" position={[0, -0.063, 0]}>
                      <group name="tail_1_27" position={[0, -0.219, 0]}>
                        <mesh
                          name="Object_47"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_47.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="tail_2_29" position={[0, -0.063, 0]}>
                        <group name="tail_2_28" position={[0, -0.156, 0]}>
                          <mesh
                            name="Object_50"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_50.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="wing_0_35" position={[-0.047, 0, 0.063]}>
                    <group name="wingtip_0_33" position={[0, 0, 0.125]}>
                      <group
                        name="wingtip_0_32"
                        position={[0.047, -0.375, -0.188]}
                      >
                        <mesh
                          name="Object_54"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_54.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="wing_0_34" position={[0.047, -0.375, -0.063]}>
                      <mesh
                        name="Object_56"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_56.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                  <group name="wing_1_39" position={[0.047, 0, 0.063]}>
                    <group name="wing_1_36" position={[-0.047, -0.375, -0.063]}>
                      <mesh
                        name="Object_59"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_59.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="wingtip_1_38" position={[0, 0, 0.125]}>
                      <group
                        name="wingtip_1_37"
                        position={[-0.047, -0.375, -0.188]}
                      >
                        <mesh
                          name="Object_62"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_62.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="rightItem_40" position={[0, -0.063, -0.188]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Allay;
