/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kuzneciv (https://sketchfab.com/kuznecivBlender)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bee-minecraft-b883baf691204b4d9a618e5e5841adf1
Title: Bee minecraft
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import MinecraftBee from "../assets/3d/bee_minecraft.glb";
import { useFrame } from "@react-three/fiber";

const Bee = ({ worldPosRot, BeePosition, ...props }) => {
  const BeeRef = useRef();
  const { nodes, materials, animations } = useGLTF(MinecraftBee);
  const { actions } = useAnimations(animations, BeeRef);

  useFrame(({ clock }) => {
    actions["Animation"].play();
    if (worldPosRot) {
      // Adjusting the x and z positions
      BeeRef.current.position.x =
        worldPosRot.worldPosition[0] + BeePosition.position[0];
      BeeRef.current.position.z =
        worldPosRot.worldPosition[2] + BeePosition.position[2];

      // Oscillating the y position using a sine wave
      const yOffset = Math.sin(Date.now() * 0.001) * 0.2;
      BeeRef.current.position.y =
        worldPosRot.worldPosition[1] + BeePosition.position[1] + yOffset;

      // Setting the rotation
      BeeRef.current.rotation.x = BeePosition.rotation[0];
      BeeRef.current.rotation.y = BeePosition.rotation[1];
      BeeRef.current.rotation.z = BeePosition.rotation[2];
    }else if(!BeePosition){
      const time = clock.elapsedTime; // Get the elapsed time
      const oscX = Math.sin(time * 0.5) * 0.1; // Adjust frequency and amplitude for X-axis oscillation
      const oscY = Math.cos(time * 0.4) * 0.1; // Adjust frequency and amplitude for Y-axis oscillation
      const oscZ = Math.sin(time * 0.3) * 0.05; // Adjust frequency and amplitude for Z-axis oscillation
      BeeRef.current.position.x = props.position[0] + oscX;
      BeeRef.current.position.y = props.position[1] + oscY;
      BeeRef.current.position.z = props.position[2] + oscZ;
    }
  });
  return (
    <group ref={BeeRef} {...props} scale={[0.1, 0.1, 0.1]} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Bee_0" scale={[1.78, 1.78, 2.967]}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials["Material.001"]}
                />
                <mesh
                  name="Object_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials["Material.002"]}
                />
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials["Material.003"]}
                />
                <mesh
                  name="Object_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials["Material.004"]}
                />
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials["Material.005"]}
                />
                <mesh
                  name="Object_9"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_9.geometry}
                  material={materials["Material.010"]}
                />
              </group>
              <group
                name="leg004_1"
                position={[1.021, -2.057, -0.8]}
                rotation={[-2.431, 0, 0]}
              >
                <mesh
                  name="Object_11"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_11.geometry}
                  material={materials["Material.013"]}
                />
              </group>
              <group
                name="USR_2"
                position={[0.79, 1.884, -4.264]}
                rotation={[0, 0, Math.PI / 2]}
                scale={[1.092, 1.042, 1.042]}
              >
                <mesh
                  name="Object_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials["Material.009"]}
                />
              </group>
              <group
                name="USL_3"
                position={[-1.052, 1.884, -4.264]}
                rotation={[0, 0, Math.PI / 2]}
                scale={[1.092, 1.042, 1.042]}
              >
                <mesh
                  name="Object_15"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_15.geometry}
                  material={materials["Material.009"]}
                />
              </group>
              <group
                name="RingL_4"
                position={[-1.728, 2.228, -1.242]}
                rotation={[2.997, 0.256, -2.854]}
                scale={[1, 1, 0.916]}
              >
                <mesh
                  name="Object_17"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_17.geometry}
                  material={materials["Material.014"]}
                />
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials["Material.011"]}
                />
              </group>
              <group
                name="RingR_5"
                position={[1.48, 2.228, -1.242]}
                rotation={[2.982, -0.237, -0.337]}
                scale={[1, 1, 0.916]}
              >
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials["Material.011"]}
                />
                <mesh
                  name="Object_21"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_21.geometry}
                  material={materials["Material.014"]}
                />
              </group>
              <group
                name="leg001_7"
                position={[-1.191, -2.057, -0.8]}
                rotation={[-2.431, 0, 0]}
              >
                <mesh
                  name="Object_23"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_23.geometry}
                  material={materials["Material.013"]}
                />
              </group>
              <group
                name="leg002_8"
                position={[1.021, -2.057, 0.375]}
                rotation={[-2.431, 0, 0]}
              >
                <mesh
                  name="Object_25"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials["Material.013"]}
                />
              </group>
              <group
                name="leg003_9"
                position={[-1.191, -2.057, 0.375]}
                rotation={[-2.431, 0, 0]}
              >
                <mesh
                  name="Object_27"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_27.geometry}
                  material={materials["Material.013"]}
                />
              </group>
              <group
                name="leg005_10"
                position={[1.021, -2.057, 1.572]}
                rotation={[-2.431, 0, 0]}
              >
                <mesh
                  name="Object_29"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_29.geometry}
                  material={materials["Material.013"]}
                />
              </group>
              <group
                name="leg006_11"
                position={[-1.191, -2.057, 1.572]}
                rotation={[-2.431, 0, 0]}
              >
                <mesh
                  name="Object_31"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_31.geometry}
                  material={materials["Material.013"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Bee;
