/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tojamerlin (https://sketchfab.com/tojamerlin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/white-flower-9e025b18a39741a4a38b197cee3cdcac
Title: white flower
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import flowerScene from "../assets/3d/colored_flower.glb"

const WhiteFlower = (props) => {
  const { nodes, materials } = useGLTF(flowerScene);
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wide_leaf_2_Petal_wild_0.geometry}
          material={materials.Petal_wild}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wide_leaf_2_Leaf_wild_0.geometry}
          material={materials.Leaf_wild}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wide_leaf_2_Stigma_wild_0.geometry}
          material={materials.Stigma_wild}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flower_patch_2_Petal_flower_patch_0.geometry}
        material={materials.Petal_flower_patch}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flower_patch_2_Leaf_flower_patch_0.geometry}
        material={materials.Leaf_flower_patch}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flower_patch_2_Stem_flower_patch_0.geometry}
        material={materials.Stem_flower_patch}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.flower_patch_2_Stigma_flower_patch_0.geometry}
        material={materials.Stigma_flower_patch}
      />
    </group>
  );
}

export default WhiteFlower;