import { useState } from "react";
import { Button, Field, FormStatus, Note, Panel, TextInput } from "./ui";
import { changePassword } from "../../lib/api/admin";

/**
 * Replacing the password.
 *
 * Shown as a wall the first time an account signs in, because the password it
 * used to get here was generated by a script, printed in a terminal and quite
 * possibly copied into a note somewhere. Until it is replaced the server
 * refuses every other route, so this screen is not something to skip past.
 *
 * The length check below is a copy of the server's, kept only so the message
 * arrives before the round trip. The server is the one that decides.
 */
const MIN_LENGTH = 12;

function AdminPasswordChange({ forced = false, username, onDone, onCancel }) {
  const [current, setCurrent] = useState("");
  const [next, setNext] = useState("");
  const [confirm, setConfirm] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);
  const [field, setField] = useState(null);

  const mismatch = confirm !== "" && next !== confirm;
  const tooShort = next !== "" && next.length < MIN_LENGTH;
  const ready = current !== "" && next.length >= MIN_LENGTH && next === confirm && !busy;

  async function handleSubmit(event) {
    event.preventDefault();
    if (!ready) return;

    setBusy(true);
    setError(null);
    setField(null);

    try {
      const result = await changePassword({ currentPassword: current, newPassword: next });
      setCurrent("");
      setNext("");
      setConfirm("");
      onDone?.(result);
    } catch (failure) {
      setError(failure.message ?? "That did not work. Try again.");
      setField(failure.field ?? null);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="flex min-h-screen w-full items-center justify-center px-4 py-16">
      <div className="w-full max-w-sm">
        <div className="pb-6 text-center">
          <span className="inline-flex h-12 w-12 items-center justify-center rounded-xl border border-amber-400/40 bg-amber-400/10 text-amber-300">
            <i className="fa-solid fa-key" aria-hidden="true" />
          </span>
          <h1 className="pt-4 text-base font-bold tracking-wide text-white">
            {forced ? "Set a real password" : "Change password"}
          </h1>
          {username && <p className="pt-1 text-xs text-ubuntu-warm-grey">Signed in as {username}</p>}
        </div>

        <Panel accent="amber" className="p-5">
          <form className="flex flex-col gap-4" onSubmit={handleSubmit} noValidate>
            {forced && (
              <Note accent="amber" icon="fa-solid fa-triangle-exclamation">
                You signed in with a temporary password. The dashboard stays closed until it
                is replaced.
              </Note>
            )}

            <Field
              label={forced ? "Temporary password" : "Current password"}
              htmlFor="admin-current"
              required
              error={field === "currentPassword" ? error : undefined}
            >
              <TextInput
                id="admin-current"
                type="password"
                accent="amber"
                autoComplete="current-password"
                invalid={field === "currentPassword"}
                value={current}
                onChange={(event) => setCurrent(event.target.value)}
                disabled={busy}
                required
              />
            </Field>

            <Field
              label="New password"
              htmlFor="admin-new"
              required
              hint={`At least ${MIN_LENGTH} characters. A passphrase of a few words is easier to type and harder to guess than a short one with symbols in it.`}
              error={
                tooShort
                  ? `That is ${next.length} of ${MIN_LENGTH} characters.`
                  : field === "newPassword"
                    ? error
                    : undefined
              }
            >
              <TextInput
                id="admin-new"
                type="password"
                accent="amber"
                autoComplete="new-password"
                invalid={tooShort || field === "newPassword"}
                value={next}
                onChange={(event) => setNext(event.target.value)}
                disabled={busy}
                required
              />
            </Field>

            <Field
              label="New password again"
              htmlFor="admin-confirm"
              required
              error={mismatch ? "The two do not match." : undefined}
            >
              <TextInput
                id="admin-confirm"
                type="password"
                accent="amber"
                autoComplete="new-password"
                invalid={mismatch}
                value={confirm}
                onChange={(event) => setConfirm(event.target.value)}
                disabled={busy}
                required
              />
            </Field>

            {error && !field && (
              <FormStatus tone="error" title="Not changed">
                {error}
              </FormStatus>
            )}

            <div className="flex flex-col gap-2">
              <Button
                accent="amber"
                type="submit"
                icon={busy ? "fa-solid fa-circle-notch fa-spin" : "fa-solid fa-check"}
                className="w-full"
                disabled={!ready}
              >
                {busy ? "Saving" : "Set password"}
              </Button>

              {!forced && (
                <Button accent="slate" variant="outline" className="w-full" onClick={onCancel} disabled={busy}>
                  Cancel
                </Button>
              )}
            </div>
          </form>
        </Panel>

        <p className="pt-5 text-center text-[11px] leading-relaxed text-slate-500">
          Changing this signs every other browser out of the account.
        </p>
      </div>
    </div>
  );
}

export default AdminPasswordChange;
